import type { Metadata } from "next";
import Script from "next/script";
import { Poppins } from 'next/font/google';
import './globals.css';
import Navbar from "@/Components/NavBar";
import Footer from "@/Components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <Script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || 'AIzaSyBXm5uF-ladXhm6MijlNeEFxyrSHO8MpCw'}&libraries=places&loading=async`}
        strategy="beforeInteractive"
      />
    </head>
    <body className={poppins.className}>
      {children}
    </body>
  </html>
  );
}

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="bg-[#F7F1EE] min-h-screen">
      <Navbar />
      <main className="max-w-full mx-auto pt-24 md:pt-28">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export { Layout };
