import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import './globals.css';
import Navbar from "@/Components/NavBar";
import Footer from "@/Components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'] // Include weights you need, e.g., 400 for regular, 700 for bold
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/* Apply the font class to the body */}
    <body className={poppins.className}>
      {children}
    </body>
  </html>
  );
}

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    // This is the main container for your entire site.
    // We apply the background color here.
    <div className="bg-[#F7F1EE] min-h-screen">
      <Navbar />
      {/* This main tag will hold the page-specific content */}
      {/* We apply the max-width and center it with mx-auto */}
      <main className="max-w-full mx-auto">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export { Layout };
